beacons per quality: 10
path qualities:
    latency:
        combination: additive
        optimality: min
        symmetry tolerance: 0.1
    throughput:
        combination: min
        optimality: max
        symmetry tolerance: 0.2